# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    docker:
      - image: docker:20.10-git
    working_directory: /ci
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: |
            docker build -t evmexp .

